# Generated by Django 2.2.1 on 2019-07-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_description', models.CharField(max_length=1000)),
                ('movie_year', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
                ('is_published', models.BooleanField(default=True)),
                ('movie_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name_one', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'category first',
            },
        ),
        migrations.CreateModel(
            name='MovieCategorySecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name_two', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'category second',
            },
        ),
        migrations.CreateModel(
            name='MovieQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Quality',
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_order_by', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Order_by',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title_content', models.CharField(max_length=100)),
                ('movie_content', models.TextField(max_length=1000)),
                ('movie_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Movie')),
                ('movie_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MovieRating')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.MovieCategory'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_category_second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.MovieCategorySecond'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Order_by'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.MovieQuality'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.MovieRating'),
        ),
    ]
