# Generated by Django 2.2.1 on 2019-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=50)),
                ('movie_title', models.CharField(max_length=2083)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
